'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34003
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace MythContent_27
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LiveStreamInfo", [Namespace]:="http://mythtv.org"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LiveStreamInfo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private WidthField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private HeightField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BitrateField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AudioBitrateField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SegmentSizeField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MaxSegmentsField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StartSegmentField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CurrentSegmentField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SegmentCountField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PercentCompleteField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CreatedField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LastModifiedField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RelativeURLField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FullURLField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusStrField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusIntField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StatusMessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceFileField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceHostField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceWidthField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SourceHeightField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AudioOnlyBitrateField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Width() As Integer
            Get
                Return Me.WidthField
            End Get
            Set
                If (Me.WidthField.Equals(value) <> true) Then
                    Me.WidthField = value
                    Me.RaisePropertyChanged("Width")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public Property Height() As Integer
            Get
                Return Me.HeightField
            End Get
            Set
                If (Me.HeightField.Equals(value) <> true) Then
                    Me.HeightField = value
                    Me.RaisePropertyChanged("Height")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public Property Bitrate() As Integer
            Get
                Return Me.BitrateField
            End Get
            Set
                If (Me.BitrateField.Equals(value) <> true) Then
                    Me.BitrateField = value
                    Me.RaisePropertyChanged("Bitrate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public Property AudioBitrate() As Integer
            Get
                Return Me.AudioBitrateField
            End Get
            Set
                If (Me.AudioBitrateField.Equals(value) <> true) Then
                    Me.AudioBitrateField = value
                    Me.RaisePropertyChanged("AudioBitrate")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public Property SegmentSize() As Integer
            Get
                Return Me.SegmentSizeField
            End Get
            Set
                If (Me.SegmentSizeField.Equals(value) <> true) Then
                    Me.SegmentSizeField = value
                    Me.RaisePropertyChanged("SegmentSize")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public Property MaxSegments() As Integer
            Get
                Return Me.MaxSegmentsField
            End Get
            Set
                If (Me.MaxSegmentsField.Equals(value) <> true) Then
                    Me.MaxSegmentsField = value
                    Me.RaisePropertyChanged("MaxSegments")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=7)>  _
        Public Property StartSegment() As Integer
            Get
                Return Me.StartSegmentField
            End Get
            Set
                If (Me.StartSegmentField.Equals(value) <> true) Then
                    Me.StartSegmentField = value
                    Me.RaisePropertyChanged("StartSegment")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=8)>  _
        Public Property CurrentSegment() As Integer
            Get
                Return Me.CurrentSegmentField
            End Get
            Set
                If (Me.CurrentSegmentField.Equals(value) <> true) Then
                    Me.CurrentSegmentField = value
                    Me.RaisePropertyChanged("CurrentSegment")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=9)>  _
        Public Property SegmentCount() As Integer
            Get
                Return Me.SegmentCountField
            End Get
            Set
                If (Me.SegmentCountField.Equals(value) <> true) Then
                    Me.SegmentCountField = value
                    Me.RaisePropertyChanged("SegmentCount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=10)>  _
        Public Property PercentComplete() As Integer
            Get
                Return Me.PercentCompleteField
            End Get
            Set
                If (Me.PercentCompleteField.Equals(value) <> true) Then
                    Me.PercentCompleteField = value
                    Me.RaisePropertyChanged("PercentComplete")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=11)>  _
        Public Property Created() As System.Nullable(Of Date)
            Get
                Return Me.CreatedField
            End Get
            Set
                If (Me.CreatedField.Equals(value) <> true) Then
                    Me.CreatedField = value
                    Me.RaisePropertyChanged("Created")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=12)>  _
        Public Property LastModified() As System.Nullable(Of Date)
            Get
                Return Me.LastModifiedField
            End Get
            Set
                If (Me.LastModifiedField.Equals(value) <> true) Then
                    Me.LastModifiedField = value
                    Me.RaisePropertyChanged("LastModified")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public Property RelativeURL() As String
            Get
                Return Me.RelativeURLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RelativeURLField, value) <> true) Then
                    Me.RelativeURLField = value
                    Me.RaisePropertyChanged("RelativeURL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=14)>  _
        Public Property FullURL() As String
            Get
                Return Me.FullURLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FullURLField, value) <> true) Then
                    Me.FullURLField = value
                    Me.RaisePropertyChanged("FullURL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=15)>  _
        Public Property StatusStr() As String
            Get
                Return Me.StatusStrField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusStrField, value) <> true) Then
                    Me.StatusStrField = value
                    Me.RaisePropertyChanged("StatusStr")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=16)>  _
        Public Property StatusInt() As Integer
            Get
                Return Me.StatusIntField
            End Get
            Set
                If (Me.StatusIntField.Equals(value) <> true) Then
                    Me.StatusIntField = value
                    Me.RaisePropertyChanged("StatusInt")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=17)>  _
        Public Property StatusMessage() As String
            Get
                Return Me.StatusMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StatusMessageField, value) <> true) Then
                    Me.StatusMessageField = value
                    Me.RaisePropertyChanged("StatusMessage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=18)>  _
        Public Property SourceFile() As String
            Get
                Return Me.SourceFileField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SourceFileField, value) <> true) Then
                    Me.SourceFileField = value
                    Me.RaisePropertyChanged("SourceFile")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=19)>  _
        Public Property SourceHost() As String
            Get
                Return Me.SourceHostField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SourceHostField, value) <> true) Then
                    Me.SourceHostField = value
                    Me.RaisePropertyChanged("SourceHost")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=20)>  _
        Public Property SourceWidth() As Integer
            Get
                Return Me.SourceWidthField
            End Get
            Set
                If (Me.SourceWidthField.Equals(value) <> true) Then
                    Me.SourceWidthField = value
                    Me.RaisePropertyChanged("SourceWidth")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=21)>  _
        Public Property SourceHeight() As Integer
            Get
                Return Me.SourceHeightField
            End Get
            Set
                If (Me.SourceHeightField.Equals(value) <> true) Then
                    Me.SourceHeightField = value
                    Me.RaisePropertyChanged("SourceHeight")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=22)>  _
        Public Property AudioOnlyBitrate() As Integer
            Get
                Return Me.AudioOnlyBitrateField
            End Get
            Set
                If (Me.AudioOnlyBitrateField.Equals(value) <> true) Then
                    Me.AudioOnlyBitrateField = value
                    Me.RaisePropertyChanged("AudioOnlyBitrate")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfString", [Namespace]:="http://mythtv.org", ItemName:="String"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfString
        Inherits System.Collections.Generic.List(Of String)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LiveStreamInfoList", [Namespace]:="http://mythtv.org"),  _
     System.SerializableAttribute()>  _
    Partial Public Class LiveStreamInfoList
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LiveStreamInfosField() As MythContent_27.LiveStreamInfo
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property LiveStreamInfos() As MythContent_27.LiveStreamInfo()
            Get
                Return Me.LiveStreamInfosField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LiveStreamInfosField, value) <> true) Then
                    Me.LiveStreamInfosField = value
                    Me.RaisePropertyChanged("LiveStreamInfos")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ArtworkInfoList", [Namespace]:="http://mythtv.org"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ArtworkInfoList
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ArtworkInfosField() As MythContent_27.ArtworkInfo
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ArtworkInfos() As MythContent_27.ArtworkInfo()
            Get
                Return Me.ArtworkInfosField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ArtworkInfosField, value) <> true) Then
                    Me.ArtworkInfosField = value
                    Me.RaisePropertyChanged("ArtworkInfos")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="ArtworkInfo", [Namespace]:="http://mythtv.org"),  _
     System.SerializableAttribute()>  _
    Partial Public Class ArtworkInfo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private URLField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FileNameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StorageGroupField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TypeField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property URL() As String
            Get
                Return Me.URLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.URLField, value) <> true) Then
                    Me.URLField = value
                    Me.RaisePropertyChanged("URL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property FileName() As String
            Get
                Return Me.FileNameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FileNameField, value) <> true) Then
                    Me.FileNameField = value
                    Me.RaisePropertyChanged("FileName")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property StorageGroup() As String
            Get
                Return Me.StorageGroupField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StorageGroupField, value) <> true) Then
                    Me.StorageGroupField = value
                    Me.RaisePropertyChanged("StorageGroup")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property Type() As String
            Get
                Return Me.TypeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TypeField, value) <> true) Then
                    Me.TypeField = value
                    Me.RaisePropertyChanged("Type")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://mythtv.org", ConfigurationName:="MythContent_27.Content")>  _
    Public Interface Content
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/AddLiveStream", ReplyAction:="http://mythtv.org/Content/AddLiveStreamResponse")>  _
        Function AddLiveStream(ByVal StorageGroup As String, ByVal FileName As String, ByVal HostName As String, ByVal MaxSegments As System.Nullable(Of Integer), ByVal Width As System.Nullable(Of Integer), ByVal Height As System.Nullable(Of Integer), ByVal Bitrate As System.Nullable(Of Integer), ByVal AudioBitrate As System.Nullable(Of Integer), ByVal SampleRate As System.Nullable(Of Integer)) As MythContent_27.LiveStreamInfo
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/AddRecordingLiveStream", ReplyAction:="http://mythtv.org/Content/AddRecordingLiveStreamResponse")>  _
        Function AddRecordingLiveStream(ByVal ChanId As System.Nullable(Of Integer), ByVal StartTime As System.Nullable(Of Date), ByVal MaxSegments As System.Nullable(Of Integer), ByVal Width As System.Nullable(Of Integer), ByVal Height As System.Nullable(Of Integer), ByVal Bitrate As System.Nullable(Of Integer), ByVal AudioBitrate As System.Nullable(Of Integer), ByVal SampleRate As System.Nullable(Of Integer)) As MythContent_27.LiveStreamInfo
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/AddVideoLiveStream", ReplyAction:="http://mythtv.org/Content/AddVideoLiveStreamResponse")>  _
        Function AddVideoLiveStream(ByVal Id As System.Nullable(Of Integer), ByVal MaxSegments As System.Nullable(Of Integer), ByVal Width As System.Nullable(Of Integer), ByVal Height As System.Nullable(Of Integer), ByVal Bitrate As System.Nullable(Of Integer), ByVal AudioBitrate As System.Nullable(Of Integer), ByVal SampleRate As System.Nullable(Of Integer)) As MythContent_27.LiveStreamInfo
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/DownloadFile", ReplyAction:="http://mythtv.org/Content/DownloadFileResponse")>  _
        Function DownloadFile(ByVal URL As String, ByVal StorageGroup As String) As System.Nullable(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/GetAlbumArt", ReplyAction:="http://mythtv.org/Content/GetAlbumArtResponse")>  _
        Function GetAlbumArt(ByVal Id As System.Nullable(Of Integer), ByVal Width As System.Nullable(Of Integer), ByVal Height As System.Nullable(Of Integer)) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/GetFile", ReplyAction:="http://mythtv.org/Content/GetFileResponse")>  _
        Function GetFile(ByVal StorageGroup As String, ByVal FileName As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/GetFileList", ReplyAction:="http://mythtv.org/Content/GetFileListResponse")>  _
        Function GetFileList(ByVal StorageGroup As String) As MythContent_27.ArrayOfString
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/GetHash", ReplyAction:="http://mythtv.org/Content/GetHashResponse")>  _
        Function GetHash(ByVal StorageGroup As String, ByVal FileName As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/GetImageFile", ReplyAction:="http://mythtv.org/Content/GetImageFileResponse")>  _
        Function GetImageFile(ByVal StorageGroup As String, ByVal FileName As String, ByVal Width As System.Nullable(Of Integer), ByVal Height As System.Nullable(Of Integer)) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/GetLiveStream", ReplyAction:="http://mythtv.org/Content/GetLiveStreamResponse")>  _
        Function GetLiveStream(ByVal Id As System.Nullable(Of Integer)) As MythContent_27.LiveStreamInfo
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/GetLiveStreamList", ReplyAction:="http://mythtv.org/Content/GetLiveStreamListResponse")>  _
        Function GetLiveStreamList(ByVal FileName As String) As MythContent_27.LiveStreamInfoList
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/GetMusic", ReplyAction:="http://mythtv.org/Content/GetMusicResponse")>  _
        Function GetMusic(ByVal Id As System.Nullable(Of Integer)) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/GetPreviewImage", ReplyAction:="http://mythtv.org/Content/GetPreviewImageResponse")>  _
        Function GetPreviewImage(ByVal ChanId As System.Nullable(Of Integer), ByVal StartTime As System.Nullable(Of Date), ByVal Width As System.Nullable(Of Integer), ByVal Height As System.Nullable(Of Integer), ByVal SecsIn As System.Nullable(Of Integer)) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/GetProgramArtworkList", ReplyAction:="http://mythtv.org/Content/GetProgramArtworkListResponse")>  _
        Function GetProgramArtworkList(ByVal Inetref As String, ByVal Season As System.Nullable(Of Integer)) As MythContent_27.ArtworkInfoList
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/GetRecording", ReplyAction:="http://mythtv.org/Content/GetRecordingResponse")>  _
        Function GetRecording(ByVal ChanId As System.Nullable(Of Integer), ByVal StartTime As System.Nullable(Of Date)) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/GetRecordingArtwork", ReplyAction:="http://mythtv.org/Content/GetRecordingArtworkResponse")>  _
        Function GetRecordingArtwork(ByVal Type As String, ByVal Inetref As String, ByVal Season As System.Nullable(Of Integer), ByVal Width As System.Nullable(Of Integer), ByVal Height As System.Nullable(Of Integer)) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/GetRecordingArtworkList", ReplyAction:="http://mythtv.org/Content/GetRecordingArtworkListResponse")>  _
        Function GetRecordingArtworkList(ByVal ChanId As System.Nullable(Of Integer), ByVal StartTime As System.Nullable(Of Date)) As MythContent_27.ArtworkInfoList
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/GetVideo", ReplyAction:="http://mythtv.org/Content/GetVideoResponse")>  _
        Function GetVideo(ByVal Id As System.Nullable(Of Integer)) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/GetVideoArtwork", ReplyAction:="http://mythtv.org/Content/GetVideoArtworkResponse")>  _
        Function GetVideoArtwork(ByVal Type As String, ByVal Id As System.Nullable(Of Integer), ByVal Width As System.Nullable(Of Integer), ByVal Height As System.Nullable(Of Integer)) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/RemoveLiveStream", ReplyAction:="http://mythtv.org/Content/RemoveLiveStreamResponse")>  _
        Function RemoveLiveStream(ByVal Id As System.Nullable(Of Integer)) As System.Nullable(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://mythtv.org/Content/StopLiveStream", ReplyAction:="http://mythtv.org/Content/StopLiveStreamResponse")>  _
        Function StopLiveStream(ByVal Id As System.Nullable(Of Integer)) As MythContent_27.LiveStreamInfo
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ContentChannel
        Inherits MythContent_27.Content, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ContentClient
        Inherits System.ServiceModel.ClientBase(Of MythContent_27.Content)
        Implements MythContent_27.Content
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function AddLiveStream(ByVal StorageGroup As String, ByVal FileName As String, ByVal HostName As String, ByVal MaxSegments As System.Nullable(Of Integer), ByVal Width As System.Nullable(Of Integer), ByVal Height As System.Nullable(Of Integer), ByVal Bitrate As System.Nullable(Of Integer), ByVal AudioBitrate As System.Nullable(Of Integer), ByVal SampleRate As System.Nullable(Of Integer)) As MythContent_27.LiveStreamInfo Implements MythContent_27.Content.AddLiveStream
            Return MyBase.Channel.AddLiveStream(StorageGroup, FileName, HostName, MaxSegments, Width, Height, Bitrate, AudioBitrate, SampleRate)
        End Function
        
        Public Function AddRecordingLiveStream(ByVal ChanId As System.Nullable(Of Integer), ByVal StartTime As System.Nullable(Of Date), ByVal MaxSegments As System.Nullable(Of Integer), ByVal Width As System.Nullable(Of Integer), ByVal Height As System.Nullable(Of Integer), ByVal Bitrate As System.Nullable(Of Integer), ByVal AudioBitrate As System.Nullable(Of Integer), ByVal SampleRate As System.Nullable(Of Integer)) As MythContent_27.LiveStreamInfo Implements MythContent_27.Content.AddRecordingLiveStream
            Return MyBase.Channel.AddRecordingLiveStream(ChanId, StartTime, MaxSegments, Width, Height, Bitrate, AudioBitrate, SampleRate)
        End Function
        
        Public Function AddVideoLiveStream(ByVal Id As System.Nullable(Of Integer), ByVal MaxSegments As System.Nullable(Of Integer), ByVal Width As System.Nullable(Of Integer), ByVal Height As System.Nullable(Of Integer), ByVal Bitrate As System.Nullable(Of Integer), ByVal AudioBitrate As System.Nullable(Of Integer), ByVal SampleRate As System.Nullable(Of Integer)) As MythContent_27.LiveStreamInfo Implements MythContent_27.Content.AddVideoLiveStream
            Return MyBase.Channel.AddVideoLiveStream(Id, MaxSegments, Width, Height, Bitrate, AudioBitrate, SampleRate)
        End Function
        
        Public Function DownloadFile(ByVal URL As String, ByVal StorageGroup As String) As System.Nullable(Of Boolean) Implements MythContent_27.Content.DownloadFile
            Return MyBase.Channel.DownloadFile(URL, StorageGroup)
        End Function
        
        Public Function GetAlbumArt(ByVal Id As System.Nullable(Of Integer), ByVal Width As System.Nullable(Of Integer), ByVal Height As System.Nullable(Of Integer)) As String Implements MythContent_27.Content.GetAlbumArt
            Return MyBase.Channel.GetAlbumArt(Id, Width, Height)
        End Function
        
        Public Function GetFile(ByVal StorageGroup As String, ByVal FileName As String) As String Implements MythContent_27.Content.GetFile
            Return MyBase.Channel.GetFile(StorageGroup, FileName)
        End Function
        
        Public Function GetFileList(ByVal StorageGroup As String) As MythContent_27.ArrayOfString Implements MythContent_27.Content.GetFileList
            Return MyBase.Channel.GetFileList(StorageGroup)
        End Function
        
        Public Function GetHash(ByVal StorageGroup As String, ByVal FileName As String) As String Implements MythContent_27.Content.GetHash
            Return MyBase.Channel.GetHash(StorageGroup, FileName)
        End Function
        
        Public Function GetImageFile(ByVal StorageGroup As String, ByVal FileName As String, ByVal Width As System.Nullable(Of Integer), ByVal Height As System.Nullable(Of Integer)) As String Implements MythContent_27.Content.GetImageFile
            Return MyBase.Channel.GetImageFile(StorageGroup, FileName, Width, Height)
        End Function
        
        Public Function GetLiveStream(ByVal Id As System.Nullable(Of Integer)) As MythContent_27.LiveStreamInfo Implements MythContent_27.Content.GetLiveStream
            Return MyBase.Channel.GetLiveStream(Id)
        End Function
        
        Public Function GetLiveStreamList(ByVal FileName As String) As MythContent_27.LiveStreamInfoList Implements MythContent_27.Content.GetLiveStreamList
            Return MyBase.Channel.GetLiveStreamList(FileName)
        End Function
        
        Public Function GetMusic(ByVal Id As System.Nullable(Of Integer)) As String Implements MythContent_27.Content.GetMusic
            Return MyBase.Channel.GetMusic(Id)
        End Function
        
        Public Function GetPreviewImage(ByVal ChanId As System.Nullable(Of Integer), ByVal StartTime As System.Nullable(Of Date), ByVal Width As System.Nullable(Of Integer), ByVal Height As System.Nullable(Of Integer), ByVal SecsIn As System.Nullable(Of Integer)) As String Implements MythContent_27.Content.GetPreviewImage
            Return MyBase.Channel.GetPreviewImage(ChanId, StartTime, Width, Height, SecsIn)
        End Function
        
        Public Function GetProgramArtworkList(ByVal Inetref As String, ByVal Season As System.Nullable(Of Integer)) As MythContent_27.ArtworkInfoList Implements MythContent_27.Content.GetProgramArtworkList
            Return MyBase.Channel.GetProgramArtworkList(Inetref, Season)
        End Function
        
        Public Function GetRecording(ByVal ChanId As System.Nullable(Of Integer), ByVal StartTime As System.Nullable(Of Date)) As String Implements MythContent_27.Content.GetRecording
            Return MyBase.Channel.GetRecording(ChanId, StartTime)
        End Function
        
        Public Function GetRecordingArtwork(ByVal Type As String, ByVal Inetref As String, ByVal Season As System.Nullable(Of Integer), ByVal Width As System.Nullable(Of Integer), ByVal Height As System.Nullable(Of Integer)) As String Implements MythContent_27.Content.GetRecordingArtwork
            Return MyBase.Channel.GetRecordingArtwork(Type, Inetref, Season, Width, Height)
        End Function
        
        Public Function GetRecordingArtworkList(ByVal ChanId As System.Nullable(Of Integer), ByVal StartTime As System.Nullable(Of Date)) As MythContent_27.ArtworkInfoList Implements MythContent_27.Content.GetRecordingArtworkList
            Return MyBase.Channel.GetRecordingArtworkList(ChanId, StartTime)
        End Function
        
        Public Function GetVideo(ByVal Id As System.Nullable(Of Integer)) As String Implements MythContent_27.Content.GetVideo
            Return MyBase.Channel.GetVideo(Id)
        End Function
        
        Public Function GetVideoArtwork(ByVal Type As String, ByVal Id As System.Nullable(Of Integer), ByVal Width As System.Nullable(Of Integer), ByVal Height As System.Nullable(Of Integer)) As String Implements MythContent_27.Content.GetVideoArtwork
            Return MyBase.Channel.GetVideoArtwork(Type, Id, Width, Height)
        End Function
        
        Public Function RemoveLiveStream(ByVal Id As System.Nullable(Of Integer)) As System.Nullable(Of Boolean) Implements MythContent_27.Content.RemoveLiveStream
            Return MyBase.Channel.RemoveLiveStream(Id)
        End Function
        
        Public Function StopLiveStream(ByVal Id As System.Nullable(Of Integer)) As MythContent_27.LiveStreamInfo Implements MythContent_27.Content.StopLiveStream
            Return MyBase.Channel.StopLiveStream(Id)
        End Function
    End Class
End Namespace
